version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: build
          command: |
            yarn
            yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install nanobox
          command: |
            bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
            nanobox config set ci-mode true
            nanobox config set ci-sync-verbose true
      - run:
          name: Nanobox Deploy
          command: |
            nanobox remote add brewmap
            nanobox deploy

workflows:
  version: 2
  build and deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
