version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install nanobox
          command: |
            bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
            # nanobox-update
            nanobox config set ci-mode true
            nanobox config set ci-sync-verbose true
            sudo nanobox server --trace &
            sleep 5
      - run:
          name: Nanobox Deploy
          command: |
            nanobox remote add brewmap
            nanobox deploy
